swagger: '2.0'
info:
  version: 1.0.0
  title: Rept.ly
  description: >
    #### Allows users to see exotic Animals
basePath: /
parameters:
#   year:
#     name: year
#     in: path
#     description: The year of the memories
#     type: integer
#     required: true
definitions:
  AnimalCollection:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/AnimalResource'
  ShelterCollection:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/ShelterResource'
  LocationCollection:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/LocationResource'
  # MemoryDocument:
  #   type: object
  #   properties:
  #     data:
  #       $ref: '#/definitions/MemoryResource'
  AnimalResource:
    type: object
    properties:
      type:
        type: string
        enum:
        - Animal
      id:
        type: integer
      attributes:
        $ref: '#/definitions/Animal'
  Animal:
    type: object
    properties:
      name:
        type: string
      age:
        type: string
      type:
        type: string
  Error:
    type: object
    properties:
      error:
        type: array
        items:
          type: object
          properties:
            status:
              type: string
            source:
              type: object
              properties:
                pointer:
                  type: string
            title:
              type: string
            details:
              type: string
  ShelterResource:
    type: object
    properties:
      type:
        type: string
        enum:
        - Shelter
      id:
        type: integer
      attributes:
        $ref: '#/definitions/Shelter'
  Shelter:
    type: object
    properties:
      name:
        type: string
  Error:
    type: object
    properties:
      error:
        type: array
        items:
          type: object
          properties:
            status:
              type: string
            source:
              type: object
              properties:
                pointer:
                  type: string
            title:
              type: string
            details:
              type: string
  LocationResource:
    type: object
    properties:
      type:
        type: string
        enum:
        - Location
      id:
        type: integer
      attributes:
        $ref: '#/definitions/Location'
  Location:
    type: object
    properties:
      city:
        type: string
      state:
        type: string
      zip:
        type: integer
  Error:
    type: object
    properties:
      error:
        type: array
        items:
          type: object
          properties:
            status:
              type: string
            source:
              type: object
              properties:
                pointer:
                  type: string
            title:
              type: string
            details:
              type: string
paths:
  '/animals':
    get:
      description: >
        Lists all Animals
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/AnimalCollection'
  '/shelters':
    get:
      description: >
        Lists all Shelters
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ShelterCollection'
  '/locations':
    get:
      description: >
        Lists all locations
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/LocationCollection'
  # '/memories/{year}':
  #   get:
  #     parameters:
  #       - $ref: '#/parameters/year'
  #     description: >
  #       Lists all memories for a given year
  #     responses:
  #       '200':
  #         description: Success
  #         schema:
  #           $ref: '#/definitions/MemoryCollection'
  # '/memories/years':
  #   get:
  #     description: >
  #       Lists the unique years
  #     responses:
  #       '200':
  #         description: Success
  #         schema:
  #           type: object
  #           properties:
  #             links:
  #               $ref: '#/definitions/Links'
  #             data:
  #               type: array
  #               items:
  #                 type: integer
